#+TITLE: CSS3学习笔记

* 选择器
  
** 属性选择器
   1. [att=val]
   2. [att*=val]
      如果元素用att表示的属性之属性值中包含用val指定的字符的话，则该元
      素使用这个样式。
   3. [att^=val]
      如果元素用att表示的属性之属性值的开头字符为用val指定的字符的话,
      则该元素使用这个样式。
   4. [att$=val]
      如果元素用att表示的属性之属性值的结尾字符为用val指定的字符的话,
      则该元素使用这个样式。

** 伪类选择器
   伪类选择器是CSS中已经定义好的选择器，不能随便起名。
   在CSS中，常用的伪类选择器是使用在a(锚)元素上的几种选择器，它们的使
   用方法如下：
   #+BEGIN_SRC html
     a:link { }
     a:visited { }
     a:hover { }
     a:active {}
   #+END_SRC
*** 伪元素选择器
    伪元素选择器是针对CSS中已经定义好的伪元素使用的选择器，它的使用方
    法如下：
    : 选择器：伪元素{属性：值}
    伪元素也可以与类配合使用，使用方法如下：
    : 选择器 类名：伪元素{属性：值}

    在CSS中，主要有如下4个伪元素选择器：
    - first-line
      为元素中的第一行方案使用样式。
    - first-letter
      为元素中的文字首字母或第一个字使用样式。
    - before
      在某元素之前插入一些内容。
    - after
      在某元素之后插入一些内容。
*** 结构性伪类选择器
    1. root选择器
       将样式绑定到页面的根元素中。
       #+BEGIN_SRC html
         <style type="text/css">
           :root{
           background-color: yellow;
           }
           body{
           background-color: limegreen;
           }
         </style>       
       #+END_SRC
    2. not选择器
       #+BEGIN_SRC html
         <style type="text/css">
           body *:not(h1) {
           background-color: yellow;
           }
         </style>       
       #+END_SRC
    3. empty选择器
       指定当元素内容为空时的样式
       #+BEGIN_SRC html
         <style type="text/css">
           :empty {
           background-color: yellow;
           }
         </style>       
       #+END_SRC
    4. target选择器
       对页面中某个target元素（该元素的id被当做页面中的超链接来使用）
       指定样式，该样式只在用户点击了页面中的超链接，并且跳转到target
       元素后起作用。
*** 子元素选择器
    first-child, last-child, nth-child, nth-last-child.

    nth-of-type, nth-last-type.
    
    针对同类型的子元素

    only-child

    当父元素只有一个子元素才有的样式。
*** UI元素状态伪类选择器
    共有11种：E:hover, E:active, E:focus, E:enabled, E:disabled,
    E:read-only, E:read-write, E:checked, E:default, E:indeterminate,
    E::selection.
*** 通用兄弟元素选择器
    : 子元素-兄弟元素{}
    
